name: Terraform GCP Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.6

    - name: Set up Google Cloud Credentials
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > $HOME/gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json" >> $GITHUB_ENV
        ls -lah $HOME  # Debug: Check if the file exists
        # cat $HOME/gcp-key.json  # REMOVE THIS LINE IN PRODUCTION: Do not print the credentials
      shell: bash

    - name: Authenticate with Google Cloud
      run: |
        gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
        gcloud auth list
      shell: bash

    - name: Terraform Init
      run: |
        echo "Using credentials: $GOOGLE_APPLICATION_CREDENTIALS"
        terraform init
      shell: bash

    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"
      shell: bash

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="terraform.tfvars"
      shell: bash
