name: Upgrade Cloud SQL

on:
  push:
    branches:
      - main  # Run when changes are pushed to main

jobs:
  upgrade-cloudsql:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Authenticate with GCP
    - name: Authenticate to GCP
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=gcp-key.json" >> $GITHUB_ENV
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    # Step 3: Create a Backup Before Upgrade (Recommended)
    - name: Create Backup
      run: |
        gcloud sql backups create --instance=my-instance2
        echo "Backup created successfully!"

    # Step 4: Start Upgrade Process
    - name: Start Upgrade
      id: upgrade
      run: |
        OPERATION_ID=$(gcloud sql instances patch my-instance2 --database-version=MYSQL_8_0 --quiet --format="value(name)")
        echo "OPERATION_ID=$OPERATION_ID" >> $GITHUB_ENV
        echo "Upgrade started with Operation ID: $OPERATION_ID"

    # Step 5: Wait for Upgrade to Complete
    - name: Wait for Upgrade to Complete
      run: |
        gcloud beta sql operations wait --project ${{ secrets.GCP_PROJECT_ID }} ${{ env.OPERATION_ID }}
        echo "Upgrade operation completed successfully!"

    # Step 6: Restart Cloud SQL Instance
    - name: Restart Cloud SQL Instance
      run: |
        gcloud sql instances restart my-instance2 --quiet
        echo "Cloud SQL instance restarted."

    # Step 7: Verify Upgrade
    - name: Verify Cloud SQL Version
      run: |
        gcloud sql instances describe my-instance2 | grep databaseVersion
